dist: xenial
sudo: false
language: scala
jdk:
- openjdk8
- openjdk11

scala:
- 2.12.10

env:
  global:
  - secure: WnYe/3aAebXDQi1DjKaNSRAQOsx6bZUlf5Q6qh8rPK5QBVxl3MaYh2oTOi662T7A8+hOcItXqX5zfBYJbhaXRPnL8aFm0pMrRj1j5MmQNBSwrfOaCxxKmk2NNI+Q+N7biyJ2Qiu2WGMQmNqWnpbQbiX17+qOIKduH6hKF3XGQuxdV3IUKg1Ks/4ZjfpVHyA/GFjPBJuGXNlCtI9yzIMWafM3garZ24Rf6pKzyOinpGLCnkiRt0NMSSVRFA2IpTOYwWNQN8Qnw8MhAh+fair64tyHABgMIyzfNxvV9hSQvpicQ4UG7GT1wH/Pu8qvOrVTJRkGTxRJEq4txbUWIJJZjM0rgxz7q3bqKiE7zqOI4G5bP/ZN8qNq5WhJ66S8vwB3dgMjBFMOgJO3IC1/hHJT531kFd6btOzNg8lX3PVGmJ5YwJ/9SfSYMA3SoKvKNvoCqntACl+/abLH5PyhW+HTe/lQcUqXfKuwlT7uzef3dvESqioS3yCtLL818bJjqTH8scg1l3F2dRs+qouWbR+qqz4dTlLL9fEWStOjyzL3y4K/YAZE879yYoAeWJ8+776d6jRzZXDNpznPUWBadLxQYPBNoxMV4+fJvs99Efabv6+USiSgirSs/wkWJN+pHt5c5iZ6nkjW0ASMbf3u3+gaU0UP/hKDZ5XgyzUyxLT1ris=
  - secure: LihtasWOIotQAgO+qHW+m8l7L3WCmY1ujLiXfHzm9C7A5vRFkC5dbVR36dNw+HS7uXnJZDp+nNRSA38ZfN40ZKl3Baur9PH32MitgfKhQngpKCkjLldrJ+eQ0srb5nTzVp5e70a2IccHQiPv29aIV7rY9ENNhtZU7OOruAG1i5NbIunaKEYhdyaIqtP5LWzpRD5si96vPzxQIdEPFedqm21c4FY66sjP/1eml0Zny0BNJ2XC8elsmnZkzx72f0OfjVXkE295l7amyIfn08O+dmTT4sj8Z6I6GeMEjHbzHBqo8KZ4NdbZX5Im9kaMSmcYl7vYYONvQInZ6p/AuLUj1BDPC8nRz1G8uCOiH+dJ1UQo6xwLcVJ5iImisvKIhf/Xf/QVZmIFOlcL4qGDU4yjbvux4IrxkPAsYd4urITc7T6RLbwernPKz4oplKoie+JVHOSM5i8NUhMWZo4JF1bFDwkr9P7BzsbD7G7CCCFy+nfcsE0OhTGktO51nqNIIsAO5QhVdKQSY3SZaq7VPxFheiwQLTwYpbFzFqnNWCLwGzY4RoRTPqxiyIOj6SofFAOnbL+9FBEAjeKxV/21wnqbfk5iHbQ9oulhpM+mtX2yw1S8ImxQ9oe1PHWN1MJdEyqGHx1wbz7aGI9iGFLAnUmUWkUZ5CuHsKxh/uwu7uZYh4s=
  - secure: rl+J/CCRsEaIkR7w3dmzb6h52bV+yxI4UzN7IFmwIZtWDo6dZ8zu1H+O2giCs9RwYr3m191MSAUHDm8YWcwLEvsV/Sqsxb3Vxx8jTpsuLW8yg9kZ4z96p5Ly1l9Uox824OZNPXs63ARdBxA7uaZsgoMmf1jFPuErvsfiq4FffMZYGbVEjsMgJfdI/FcDJimZvVFGQP2/1b4tPm3PAJ2+eXM0PX7em4Wdob9UuReIlIui8D4LzPQ4Uvyq27Jq0jUH/e53l7jAB4fSzFPhs3AppSOheKInEWz/IKurwbtiYuzTR4/OvbMW9wqAgUWe2aPSHSa8HHxgCM0x9DvJ1d2FvGt9iHOld7CGDIJHVA0zgMtKS0o6tkERIboUVUzlAqDpbz/9CdYJ/WHNZoZZucRQlAHy1dPjE83uGjnS7W8yjNW74/1NIRzZhReeQPCrlic2m3vEeN9dRR+n4Z4ibgAprjE9GO5yfBPDBer78NleVMra6pYiLOLPCitetkZOdayp0+q5SM4rDBLVbS56fwPJ0wMZyewQ8pTUFakJMlZseKcaaLib8M3cLefk29ktD43D36n/ZE492Je/yek3VLmU2MC189pbqCe/9z6+7J+nEo6zrPp213a1/OMDXvZJ85uUNiWSQAZO7JYv5KTNte6+wKogmz2iH9Ut+4MNPKYF6PQ=

before_install:
- if [[ -n "${TRAVIS_TAG}" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_8a4bd8b95e8a_key -iv $encrypted_8a4bd8b95e8a_iv -in .travis/secrets.tar.enc -out .travis/local.secrets.tar -d; tar xv -C .travis -f .travis/local.secrets.tar;
  fi

script:
- sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck scalafmtSbtCheck clean coverage test

after_success:
- sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
- if [[ -n "${TRAVIS_TAG}" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    sbt -Dsbt.color=always -Dsbt.supershell=false ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
- bash <(curl -s https://codecov.io/bash)

before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
