sudo: false

language: scala

jdk:
  - openjdk8
  - openjdk11

scala:
  - 2.12.10

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck scalafmtSbtCheck clean coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
  - if [[ -n "${TRAVIS_TAG}" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then sbt -Dsbt.color=always -Dsbt.supershell=false ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
